version: '3.8'

services:
  spotifyfetch:
    build:
      context: .
    volumes:
      - ./logs:/logs
    networks:
      - portfolio_network
    restart: unless-stopped

networks:
  portfolio_network:
    external: true
