version: '3.8'

services:
  spotifyfetch:
    build: .
    environment:
      - SPOTIPY_CLIENT_ID=yourid
      - SPOTIPY_CLIENT_SECRET=yoursecret
      - SPOTIPY_REDIRECT_URI=yourcallbackurl
      - MONGODB_URI=yourmongouri
      - DB_NAME=yourdbname
      - COLLECTION_NAME=yourcollectionname
    volumes:
      - ./logs:/logs
    networks:
      - portfolio_network
    restart: unless-stopped

networks:
  portfolio_network:
    external: true
